# 参照：https://y-ohgi.com/introduction-docker/4_tips/docker-compose/#_4
# Dockerーcomposeのバージョン（最新を推奨）
version: '3.7'

# コンテナの定義　imgae or buildは必須
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./public:/var/www/html/public:ro
    ports:
      - 8080:80
    environment:
      PHP_HOST: app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    # ファイルに定義された環境変数を読み取り、コンテナへ定義します。
    env_file: 
      - .env.example
    # volumes:
    #   - .:/var/www/html:cached

  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql:delegated
    # Dockerfileで定義されている CMD の上書きを行います。
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 13306:3306